# -*- coding: utf-8 -*-
"""compare.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_uB7ymX0INU0iMxfUKBgiPw5tJexFb5G
"""

with open('input.txt') as f:
    lines = f.readlines()

def distance(text1, text2):
    cur = [i for i in range(len(text1) + 1)]  
    for i in range(1, len(text2) + 1):
        prev = cur 
        cur = [i] + [0 for k in range(len(text1))] 
        for j in range(1, len(text1) + 1):
            lst = [prev[j] + 1, cur[j - 1] + 1, prev[j - 1]]
            if text1[j - 1] != text2[i - 1]:
                lst[2] += 1
            cur[j] = min(lst)
    return cur[len(text1)]/(len(text1)+len(text2))

for i in range(len(lines)):
    for j in range(i+1, len(lines)):
        with open(lines[i]) as f:
            code = f.read()
        with open(lines[j]) as f:
            code2 = f.read()
        dist = distance(code, code2)
        with open('output.txt', 'w') as f:
            f.write(str(dist))